[package]
name = "streamcc"
version = "0.1.0"
authors = ["tenchd <dtench@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
siphasher = "0.3"
rand = "0.7"
